# since github UI doesn't allow fast forward merge, this action do exactly that
# and allows to merge from develop to master without creating the merge commit
# this is good for keeping history linear and same in both branches (master, develop)
# action https://github.com/sequoia-pgp/fast-forward
# discussion (when implemented, we can delete this) https://github.com/orgs/community/discussions/4618 

name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    # Only run if the comment contains the /fast-forward command.
    if: ${{ contains(github.event.comment.body, '/fast-forward')
            && github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: on-error
