
name: Build, publish to nuget

on: #on created release
  release:
    types:
      - created
  workflow_dispatch:

env:
  BLAZORSTATIC_NUGET_PKG_PATH: src/bin/Release
  NUGET_FOLDER: nugetky

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      webapp-path: ${{ env.WEBAPP_PATH }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run tests
        run: dotnet test tests/BlazorStatic.Tests/BlazorStatic.Tests.csproj --configuration Release

      - name: Run webapp and generate static files
        run: dotnet pack src/BlazorStatic.csproj --configuration Release

      - name: Copy .nupkg of BlazorStatic to destination folder
        run: |
          mkdir -p "${{ env.NUGET_FOLDER }}"
          cp ${{ env.BLAZORSTATIC_NUGET_PKG_PATH }}/*.nupkg ${{ env.NUGET_FOLDER }}

      - name: Upload NuGet package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ${{ env.NUGET_FOLDER }}/*.nupkg

  publish-to-nuget:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download NuGet package artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
      - run: dotnet nuget push "*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}
