
name: Build, publish to gh pages and nuget

on:
  push:
    branches: ["*"]
env:
  WEBAPP_PATH: BlazorStaticWebsite
  TEMPLATE_PROJ_PATH: BlazorStaticTemplates/BlazorStatic.Templates.csproj
  BLAZORSTATIC_NUGET_PKG_PATH: src/bin/Release
  NUGET_FOLDER: nugetky
  WEBAPP_CSPROJ: BlazorStaticWebsite.csproj
  ASPNETCORE_ENVIRONMENT: Production
  is_master_branch: ${{ github.ref == 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      webapp-path: ${{ env.WEBAPP_PATH }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Remove launchSettings.json (to not override ASPNETCORE_ENVIRONMENT)
        run: rm ${{ env.WEBAPP_PATH }}/Properties/launchSettings.json
      - name: Tailwind - download and run cli
        run: |
          wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss
          chmod +x /usr/local/bin/tailwindcss
          cd ${{ env.WEBAPP_PATH }}
          tailwindcss --input ./wwwroot/app.css  --output ./wwwroot/app.min.css  --minify

      - name: Run webapp and generate static files
        run: dotnet run --project ${{ env.WEBAPP_PATH }}/${{env.WEBAPP_CSPROJ}}  --configuration Release


      - name: Upload webapp output artifacts
        uses: actions/upload-artifact@v4
        with:
            name: static-pages-output
            path: ${{ env.WEBAPP_PATH }}/output

      - name: Copy .nupkg of BlazorStatic to destination folder and pack the template project there too
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          mkdir -p "${{ env.NUGET_FOLDER }}"
          cp ${{ env.BLAZORSTATIC_NUGET_PKG_PATH }}/*.nupkg ${{ env.NUGET_FOLDER }}
          dotnet pack ${{ env.TEMPLATE_PROJ_PATH }} --output ${{ env.NUGET_FOLDER }}

      - name: Upload NuGet package artifacts
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v4
        with:
            name: nuget-packages
            path: ${{ env.NUGET_FOLDER }}/*.nupkg

  deploy-to-gh-pages:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: static-pages-output
          path: output
      - run: touch output/.nojekyll #folder starting with _ are handled as jekyll. This file will prevent that.
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./output

  publish-to-nuget:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Download NuGet package artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
      - run: dotnet nuget push "*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
